[workspace]
members = [
    ".",
    "./derive",
    "examples/single_table",
]

[package]
name = "aoba"
version = "0.1.0"
edition = "2021"

[dependencies]
aoba_derive = { version = "0.1.0", path = "./derive" }
sqlx = { version = "0.6", default-features = false, features = ["runtime-async-std-native-tls", "postgres", "macros"] }

[features]
default = []

### future plan
# sqlx-asyncstd-postgres = []
# sqlx-asyncstd-mysql = []
# sqlx-tokio-postgres = []
# sqlx-tokio-mysql = []
# deadpool-asyncstd-postgres = []
# deadpool-tokio-postgres = []
