[package]
name = "single_table"
version = "0.1.0"
edition = "2021"

[dependencies]
aoba = { version = "0.1.0", path = "../../" }
sqlx = { version = "0.6", default-features = false, features = ["runtime-async-std-native-tls", "postgres", "macros"] }
